export const ANIMATION = {
  SHOOTING_STAR_MIN_INTERVAL_MS: 45_000,
  SHOOTING_STAR_MAX_INTERVAL_MS: 90_000,
  SHOOTING_STAR_DURATION_MS: 1_200,
  STAR_DRIFT_AMPLITUDE_PX: 8,
  AMBIENT_STAR_COUNT_MIN: 180,
  AMBIENT_STAR_COUNT_MAX: 220,
} as const;
